---
roles:
 - name: ome.certbot
   src: https://github.com/ome/ansible-role-certbot/archive/0.1.0.tar.gz
   version: 0.1.0

 - src: ome.cli_utils
   version: 1.1.0

 - src: ome.deploy_archive
   version: 0.1.4

#  - src: ome.docker
#    version: 3.1.1

 - src: ome.ice
   version: 4.3.0

 - src: ome.java
   version: 2.1.0

#  - name: ome.iptables_raw
#    version: 0.3.1

# - name: sco.lvm_partition
#   src: https://github.com/stephenogg/ansible-role-lvm_partition
#   version: 0.0.1

#  - name: ome.network
#    version: 1.1.4

 - src: ome.nginx
   version: 2.1.1

 - src: ome.nginx_proxy
   version: 1.15.1

#  - src: ome.nfs_mount
#    version: 1.3.0

 - src: ome.omego
   version: 0.2.0

 - src: ome.omero_common
   version: 0.3.4

 - src: ome.basedeps
   version: 1.1.0

# - src: ome.omero_prometheus_exporter
#   version: 0.3.1

 - src: ome.omero_python_deps
   version: 2.0.1

 - src: ome.omero_server
   version: 4.0.0

 - src: ome.omero_user
   version: 0.3.0

 - src: ome.omero_web
   version: 4.0.0

 - src: ome.python3_virtualenv
   version: 0.1.2

 # Delete this when everything is on Python 3
 - src: ome.omero_web_apps
   version: 0.3.0

# - src: ome.omero_web_django_prometheus
#   version: 0.4.1

 - src: ome.postgresql
   version: 5.0.2

# - src: ome.postgresql_backup
#   version: 0.2.1

 - src: ome.postgresql_client
   version: 0.1.2

# - src: ome.prometheus
#   version: 0.5.1
#
# - src: ome.prometheus_jmx
#   version: 0.3.1
#
# - src: ome.prometheus_node
#   version: 0.3.1
#
# - src: ome.prometheus_postgres
#   version: 0.4.2

 - src: ome.redis
   version: 1.1.1

 - name: ome.selinux_utils
   version: 2.0.2

 - src: ome.ssl_certificate
   version: 0.3.3

 - src: ome.sudoers
   version: 1.0.3

#  - src: ome.system_monitor_agent
#    version: 0.1.1

 - src: ome.upgrade_distpackages
   version: 1.1.3

 - src: ome.versioncontrol_utils
   version: 1.0.2
 
 - name: sco.letsencrypt
   src: https://github.com/stephenogg/ansible-role-letsencrypt
   version: 0.1.2

#  - name: sco.create_instance
#    src: https://github.com/stephenogg/ansible-role-create-instance
#
#  - name: sco.grafana
#    src: https://github.com/stephenogg/ansible-role-grafana
#    
#  - name: sco.loki
#    src: https://github.com/stephenogg/ansible-role-loki
#
#  - name: sco.promtail 
#    src: https://github.com/stephenogg/ansible-role-promtail
#    
#  - name: sco.omero_prometheus_exporter
#    src: https://github.com/stephenogg/ansible-role-omero-prometheus-exporter 
#
#  - src: cloudalchemy.prometheus
#    version: 3.0.0
#        
#  - src: cloudalchemy.blackbox-exporter
#    version: 0.9.3  
#    
#  - src: cloudalchemy.node_exporter
#    version: 2.0.0
#    
#  - src: cloudalchemy.alertmanager
#    version: 0.19.1
# 
 # My version includes the dict to select the correct ice version depending on the 
 # OS distribution. CentOS7,8 or Ubuntu18,20     
#  - name: sco.omero-prometheus-exporter
#    src: https://github.com/stephenogg/ansible-role-omero-prometheus-exporter
#    
#    
#
#collections:
# - name: openstack.cloud
#   version: 1.4.0

