---
# ansible-playbook -i <INVENTORY-DIR>/prod-hosts site.yml

# New hosts are created in Compute Candada's openstack cloud
# infrastructure. requires a named cloud "cc_arbutus_rep, cc_arbutus_default, or"
# cc_arbutus_default_dev.
# Defined in clouds.yaml file with authentication credentials specific
# for that cloud/project. Create Instance with optional second disk mounted on
# /dev/vdb to act as the OMERO binary repository.

- name: Create/Configure UofA internal instance for NicoT
  hosts: omero
  tasks:
        
    - name: configure the newly created instance
      import_playbook: productionServer.yml
        vars:
          fqdn: "omero.med.ualberta.ca"
       
        
        
       
  
    
